// export const CREATE_COURSE = 'CREATE_COURSE';
export const RESTAURANT_SEARCH = 'RESTAURANT_SEARCH';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';

// Input actions
export const UPDATE_LOCALITY = 'UPDATE_LOCALITY';
export const UPDATE_REGION = 'UPDATE_REGION';
export const UPDATE_Q = 'UPDATE_Q';
export const GET_USER_LOCATION = 'GET_USER_LOCATION';
export const SET_USER_LOCATION = 'SET_USER_LOCATION';
export const TOGGLE_LOADING_INPUT = 'TOGGLE_LOADING_INPUT';
export const CLEAR_INPUTS = 'CLEAR_INPUTS';

// Details actions
export const SET_RESTAURANT_DETAILS = 'SET_RESTAURANT_DETAILS';
export const SET_YELP_INFO = 'SET_YELP_INFO';
export const SET_FOUR_INFO = 'SET_FOUR_INFO';
export const GET_CROSSWALK = 'GET_CROSSWALK';
